spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/reqman}
    username: ${DB_USER:reqman}
    password: ${DB_PASSWORD:reqman}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

server:
  port: 8080

logging:
  level:
    root: INFO
    org.springframework.security: INFO

jwt:
  issuer: reqman-system
  access-token-expire-minutes: 30
  refresh-token-expire-days: 7
  secret: ${JWT_SECRET:Y2hhbmdlLW1lLWluLXByb2QtcGxlYXNlLWNoYW5nZS1tZS1wbGVhc2UtY2hhbmdlLW1l}

